name: FancyTimber
version: '1.0'
main: project.kompass.fancyTimber.FancyTimber
api-version: '1.21'
authors: [ JustJaimii ]
depend: [ ProtocolLib ]
description:
  Makes Illagers fight zombies. For Project: Kompass
